// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Email struct {
	ID         int32              `json:"id"`
	Title      string             `json:"title"`
	Content    pgtype.Text        `json:"content"`
	Wasseen    pgtype.Bool        `json:"wasseen"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IDReceiver int32              `json:"id_receiver"`
	IDSender   int32              `json:"id_sender"`
}

type User struct {
	ID             int32       `json:"id"`
	FullName       string      `json:"full_name"`
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	ProfilePicture pgtype.Text `json:"profile_picture"`
}
