// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name, email, password_hash
) VALUES ( $1, $2, $3)
RETURNING id, full_name, email, password_hash, profile_picture
`

type CreateUserParams struct {
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.FullName, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :execrows
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, password_hash, profile_picture
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, full_name, email, password_hash, profile_picture
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
	)
	return i, err
}

const updateUserProfilePhoto = `-- name: UpdateUserProfilePhoto :execrows
UPDATE users
SET profile_picture = $2
WHERE id = $1
`

type UpdateUserProfilePhotoParams struct {
	ID             int32       `json:"id"`
	ProfilePicture pgtype.Text `json:"profile_picture"`
}

func (q *Queries) UpdateUserProfilePhoto(ctx context.Context, arg UpdateUserProfilePhotoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfilePhoto, arg.ID, arg.ProfilePicture)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
